title: HardbassSMP 8.0
description: Link to PrismLauncher instance, list of mods, general server info.
url: https://mc.hardbass.dev
baseurl: ""

permalink: pretty

bandcamp_embed_src: "https://bandcamp.com/EmbeddedPlayer/album=1349219244/size=large/bgcol=333333/linkcol=2ebd35/tracklist=false/artwork=small/transparent=true/"

plugins:
  - jekyll-feed

exclude:
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - .template-post/
  - post-template.md